name: Run tests to solutions
on:
  pull_request:
    path:
      - solutions/**
      - exploitme*/**
  push:
    branches:
      - develop
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Run tests
        working-directory: ${{ github.workspace }}
        run: bash tests.sh
